// <auto-generated />
using System;
using GraphQL_DOTNET_CORE.Enitites.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQL_DOTNET_CORE.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQL_DOTNET_CORE.Enitites.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("OwnerId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new { Id = new Guid("da8781a4-b2d7-4f86-aa10-992c1e1ebb41"), Description = "Cash account for our users", OwnerId = new Guid("36222d91-57fc-40fa-8176-6a6fc72aa904"), Type = 0 },
                        new { Id = new Guid("cedc91a1-1e21-400e-8b6c-a465199c9c64"), Description = "Savings account for our users", OwnerId = new Guid("19282c12-da26-4d29-833e-11ecc7cd4555"), Type = 1 },
                        new { Id = new Guid("73c2f401-78ce-4e9e-a52d-295c9a030d44"), Description = "Income account for our users", OwnerId = new Guid("19282c12-da26-4d29-833e-11ecc7cd4555"), Type = 3 }
                    );
                });

            modelBuilder.Entity("GraphQL_DOTNET_CORE.Enitites.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new { Id = new Guid("36222d91-57fc-40fa-8176-6a6fc72aa904"), Address = "John Doe's address", Name = "John Doe" },
                        new { Id = new Guid("19282c12-da26-4d29-833e-11ecc7cd4555"), Address = "Jane Doe's address", Name = "Jane Doe" }
                    );
                });

            modelBuilder.Entity("GraphQL_DOTNET_CORE.Enitites.Account", b =>
                {
                    b.HasOne("GraphQL_DOTNET_CORE.Enitites.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
